[book]
authors = ["yz"]
language = "en"
multilingual = false
src = "src"
title = "learing-algorithm"

[output.html]
git-repository-url = "https://github.com/Kua-Fu/blog-book"
input-404 = "404.md"
mathjax-support = true
additional-js = ["giscus.js"]

[output.html.fold]
enable = true

[output.html.print]
enable = false