[book]
authors = ["thewind"]
description= "柴米油盐酱醋茶，琴棋书画诗酒花"
language = "en"
multilingual = false
src = "src"
title = "诗意人生"

[output.html]
git-repository-url = "https://github.com/Kua-Fu/blog-book"
input-404 = "404.md"

[output.html.fold]
enable = true

[output.html.print]
enable = false

